include:
  - project: "custom-d/ci-templates"
    file: "php-packages.latest.yml"

variables:
  PHP_IMAGE: "chialab/php-dev"
  TEST_PHP_8_2: "true"
  TEST_PHP_8_1: "true"
  TEST_PHP_8_0: "true"
  PHP_IMAGE_RELEASE_TAG: 'latest'

